-- Intentionally almost empty. Do not put reference data here.
--
-- This file is applied by `supabase db reset` against a LOCAL database only. It is
-- never applied by `db push`, which is how the hosted project is deployed. The
-- previous version of this file seeded the venue, the locations and six SKUs — and
-- because it was never applied to the hosted project, that project had no venue,
-- no location and no SKU from 27 August onwards, which is why nothing could be
-- verified against real data.
--
-- The venue, its locations and its catalogue are now reference data in
-- `migrations/202608280002_bootstrap.sql`, so local and hosted get the same rows
-- from the same source. Two copies of that list was one version of the truth too
-- many (see CLAUDE.md).
--
-- Auth users are still not seeded: `auth.users` ids are created by signing in.
-- Run `pnpm bootstrap` after the first sign-in — it claims the venue, names the
-- admin, and posts opening stock through the ledger.
